before_install:
  - sudo apt-get update -qq
  - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
language: elixir
elixir:
    - 1.0.5
otp_release:
    - 17.4
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
